<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="1" tests="3" time="0.060"><testcase classname="tests.SimpleTest" file="tests.py" line="14" name="test_fail" time="0.00118064880371"><failure message="AssertionError: 11 != 10">self = &lt;tests.SimpleTest testMethod=test_fail&gt;

    def test_fail(self):
&gt;       self.assertEqual(11, 7 + 3)
E       AssertionError: 11 != 10

tests.py:16: AssertionError</failure></testcase><testcase classname="tests.SimpleTest" file="tests.py" line="11" name="test_pass" time="0.00081992149353"></testcase><testcase classname="tests.SimpleTest" file="../../../../usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py" line="59" name="test_skipped" time="0.00104880332947"><skipped message="demonstrating skipping" type="pytest.skip">../../../../usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py:59: &lt;py._xmlgen.raw object at 0x110119d50&gt;</skipped></testcase></testsuite>